[package]
name = "rkyv_test"
version = "0.7.1"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Test suite for rkyv crates"
license = "MIT"
repository = "https://github.com/djkoloski/rkyv"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bytecheck = { version = "0.6", optional = true, default-features = false }
bytecheck = { version = "0.6", optional = true, default-features = false, git = "https://github.com/djkoloski/bytecheck", branch = "no-simdutf8" }
ptr_meta = { version = "~0.1.3", default-features = false }
rkyv = { path = "../rkyv", default-features = false }
wasm-bindgen-test = { version = "0.3", optional = true }
ahash = { version = "0.7" }

[features]
default = ["std", "size_32", "validation"]
alloc = ["rkyv/alloc"]
arbitrary_enum_discriminant = ["rkyv/arbitrary_enum_discriminant"]
archive_be = ["rkyv/archive_be"]
archive_le = ["rkyv/archive_le"]
copy = ["rkyv/copy"]
copy_unsafe = ["rkyv/copy_unsafe"]
size_16 = ["rkyv/size_16"]
size_32 = ["rkyv/size_32"]
size_64 = ["rkyv/size_64"]
std = ["alloc", "bytecheck/std", "rkyv/std"]
strict = ["rkyv/strict"]
validation = ["alloc", "bytecheck", "rkyv/validation"]
wasm = ["wasm-bindgen-test"]

# HACK: Tests should be run with `wasm-pack test --node -- --features "wasm"` but wasm-pack runs
# `cargo build` before `cargo test` and doesn't pass the additional arguments to the build step. To
# work around this, we just manually add the dependencies for the `wasm` feature when the target is
# set to `wasm32-unknown-unknown`.
# Blocking bug: https://github.com/rustwasm/wasm-pack/issues/698
[target.wasm32-unknown-unknown.dev-dependencies]
wasm-bindgen-test = "0.3"
